---
editor: 
  mode: source
crossref: 
  tbl-labels: alpha 2
---

## Table 2: Input Model Structure for AGEPRO Keyword Parameters {.unnumbered}

Note: **lengthSeqYears** is the length of a Numerical sequential vector from `GENERAL` **NFYear** to **NXyear**.

+--------------------+------------------------------------------------------------------------------------------------+
| Keyword            | Description                                                                                    |
+====================+:===============================================================================================+
| `GENERAL`          | - **NFyear**, **NXyear**, **NFage**, **NXage**, **NSims**, **NFleet**, **NRecModel**,          |
|                    |   **DiscFlag**, and **ISeed**                                                                  | 
+--------------------+------------------------------------------------------------------------------------------------+
| `CASEID`           | - **Model**                                                                                    |
+--------------------+------------------------------------------------------------------------------------------------+
| `BOOTSTRAP`        | - **NBoot**, **BootFac**                                                                       |
|                    | - **BootFile**                                                                                 |
+--------------------+------------------------------------------------------------------------------------------------+
| `HARVEST`          | - **HarvestSpec**                                                                              |
|                    | - Harvest Value:                                                                               |
|                    |   - [If **NFleet** = 1] -> Read 1 line (Harvest Value)                                         |
|                    |   - [If **NFleet** > 1] -> Read 1-**NFLEET** lines (Harvest Value)                             |
+--------------------+------------------------------------------------------------------------------------------------+
| `RETROADJUST`      | - **RetroAdjust**                                                                              |
+--------------------+------------------------------------------------------------------------------------------------+
| `NATMORT`          | - **NatMortFlag**, **NatMortTimeFlag**                                                         |
|                    | - AvgNatMort:                                                                                  |
|                    |   - [If **NatMortFlag** = 1], **datafile**                                                     |
|                    |   - [else **NatMortFlag** = 0]:                                                                |
|                    |     - [If **NatMortTimeFlag** = 1], <1:**lengthSeqYears** lines>: **AvgNatMort**               |
|                    |     - [else **NatMortTimeFlag** = 0], <1 line>: **AvgNatMort**                                 |
|                    | - **NatMortErr**                                                                               |
+--------------------+------------------------------------------------------------------------------------------------+
| `BIOLOGICAL`       | - **ZFracTimeFlag**                                                                            |
|                    | - **TF**                                                                                       |
|                    | - **TM**                                                                                       |
+--------------------+------------------------------------------------------------------------------------------------+
| `MATURITY`         | - **MaturityFlag**, **MaturityTimeFlag**                                                       |
|                    | - AvgMaturity:                                                                                 |
|                    |   - [If **MaturityFlag** = 1], **datafile**                                                    |
|                    |   - [else **Maturitylag** = 0]:                                                                |
|                    |     - [If **MaturityTimeFlag** = 1], <1:**lengthSeqYears** lines>: **AvgMaturity**             |
|                    |     - [else **MaturitytTimeFlag** = 0], <1 line>: **AvgMaturity**                              |
|                    | - **MaturityErr**                                                                              | 
+--------------------+------------------------------------------------------------------------------------------------+
| `STOCK_WEIGHT`     | - **StockWtFlag**, **StockWtTimeFlag**                                                         |
|                    | - AvgStockWeight:                                                                              |
|                    |   - [If **StockWtFlag** = 1], **datafile**                                                     |
|                    |   - [else **StockWtFlag** = 0]:                                                                |
|                    |     - [If **StockWtTimeFlag** = 1], <1:**lengthSeqYears** lines>: **AvgStockWeight**           |
|                    |     - [else **StockWtTimeFlag** = 0], <1 line>: **AvgStockWeight**                             |
|                    | - **StockWtErr**                                                                               |
+--------------------+------------------------------------------------------------------------------------------------+
| `SSB_WEIGHT`       | - **SpawnWtFlag**, **SpawnWtTimeFlag**                                                         |
|                    | - AvgSpawnWeight:                                                                              |
|                    |   - [If **SpawnWtFlag** = 1], **datafile**                                                     |
|                    |   - [else if **SpawnWtFlag** = -1] `STOCK_WEIGHT`                                              | 
|                    |   - [else **SpwanWtFlag** = 0]:                                                                |
|                    |     - [If **SpwanWtTimeFlag** = 1], <1:**lengthSeqYears** lines>: **AvgSpawnWeight**           |
|                    |     - [else **SpawnWtTimeFlag** = 0], <1 line>: **AvgSpawnWeight**                             |
|                    | - **SpawnWtErr**                                                                               |
+--------------------+------------------------------------------------------------------------------------------------+
| `MEAN_WEIGHT`      | - **MeanStockWtFlag**, **MeanStockWtTimeFlag**                                                 |
|                    | - AvgMeanStockWeight:                                                                          |
|                    |   - [If **MeanStockWtFlag** = 1], **datafile**                                                 |
|                    |   - [else if **MeanStockWtFlag** = -1], `STOCK_WEIGHT`                                         |
|                    |   - [else if **MeanStockWtFlag** = -2], `SSB_WEIGHT`                                           |
|                    |   - [else **MeanStockWtFlag** = 0]:                                                            |
|                    |     - [If **MeanStockWtTimeFlag** = 1], <1:**lengthSeqYears** lines>: **AvgMeanStockWeight**   |
|                    |     - [else **MeanStockWtTimeFlag** = 0], <1 line>: **AvgMeanStockWeight**                     |
|                    | - **MeantockWtErr**                                                                            |    
+--------------------+------------------------------------------------------------------------------------------------+
| `FISHERY`          | - **FSelecFlag**, **FSelecTimeFlag**                                                           |
|                    | - AvgFSelec:                                                                                   |
|                    |   - [If **FSelecFlag** = 1], **datafile**                                                      |
|                    |   - [else **FSelecFlag** = 0]:                                                                 |
|                    |     - [If **FSelecTimeFlag** = 1], <1:**lengthSeqYears** lines>: **AvgFSelec**                 |
|                    |     - [else **FSelecTimeFlag** = 0], <1 line>: **AvgFSelec**                                   |
|                    | - **FSelecErr**                                                                                |
+--------------------+------------------------------------------------------------------------------------------------+
| `DISCARD`          | - **DiscFracFlag**, **DiscFracTimeFlag**                                                       |
|                    | - AvgDiscFrac:                                                                                 |
|                    |   - [If **DiscFracFlag** = 1], **datafile**                                                    |
|                    |   - [else **DiscFracFlag** = 0]:                                                               |
|                    |     - [If **DiscFracTimeFlag** = 1], <1**lengthSeqYears** lines>: **AvgDiscFrac**              |
|                    |     - [else **DiscFracTimeFlag** = 0], <1 line>: **AvgDiscFrac**                               |
|                    | - **DiscFracErr**                                                                              |
+--------------------+------------------------------------------------------------------------------------------------+
| `CATCH_WEIGHT`     | - **CatchWtFlag**, **CatchWtTimeFlag**                                                         |
|                    | - AvgCatchWeight:                                                                              |
|                    |   - [If **CatchWtFlag** = 1], **datafile**                                                     |
|                    |   - [else if **CatchWtFlag** = -1] `STOCK_WEIGHT`                                              |
|                    |   - [else if **CatchWtFlag** = -2] `SSB_WEIGHT`                                                |
|                    |   - [else if **CatchWtFlag** = -3] `MEAN_WEIGHT`                                               |
|                    |   - [else **CatchWtFlag** = 0]:                                                                |
|                    |     - [If **catchWtTimeFlag** = 1], 1:<lengthfromNFYeartoNXyear> lines **AvgCatchWeight**      |
|                    |     - [else **CatchWtTimeFlag** = 0], 1 line **AvgCatchWeight**                                |
|                    | - **CatchWtErr**                                                                               |
+--------------------+------------------------------------------------------------------------------------------------+
| `DISC_WEIGHT`      | - **DiscWtFlag**, **DiscWtTimeFlag**                                                           |
|                    | - AvgDiscWeight:                                                                               |
|                    |   - [If **DiscWtFlag** = 1], **datafile**                                                      |
|                    |   - [else if **DiscWtFlag** = -1] `STOCK_WEIGHT`                                               |
|                    |   - [else if **DiscWtFlag** = -2] `SSB_WEIGHT`                                                 |
|                    |   - [else if **DiscWtFlag** = -3] `MEAN_WEIGHT`                                                |
|                    |   - [else if **DiscWtFlag** = -4] `CATCH_WEIGHT`                                               |
|                    |   - [else **DiscWtFlag** = 0]:                                                                 |
|                    |     - [If **DiscWtTimeFlag** = 1], 1:<lengthfromNFYeartoNXyear> lines **AvgDiscWeight**        |
|                    |     - [else **DiscWtTimeFlag** = 0], 1 line **AvgDiscWeight**                                  |
|                    | - **DiscWtErr**                                                                                |
+--------------------+------------------------------------------------------------------------------------------------+
| `RECRUIT`          | - **RecFac**, **SSBFac**, **MaxRecObs**                                                        |
|                    | - **RecruitType**                                                                              |
|                    | - <1:**lengthSeqYears** lines>:  Recruitment probabilty                                        |
|                    | - **recruit_data**: See Recruitment Model Vignette                                             |
+--------------------+------------------------------------------------------------------------------------------------+
| `BOUNDS`           | - **MaxWeight**, **MaxNatMort**                                                                |
+--------------------+------------------------------------------------------------------------------------------------+
| `OPTIONS`          | - **StockSummaryFlag**, **DataFlag**, **ExportRFlag**                                          |
+--------------------+------------------------------------------------------------------------------------------------+
| `SCALE`            | - **scalebio**, **scalerec**, **scalestk**                                                     |
+--------------------+------------------------------------------------------------------------------------------------+
| `PERC`             | - **PercReportValue**                                                                          |
+--------------------+------------------------------------------------------------------------------------------------+
| `REFPOINT`         | - **SSBThresh**, **StockBioThresh**, **MeanBioThresh**, **FMortThresh**                        |
+--------------------+------------------------------------------------------------------------------------------------+
| `REBUILD`          | - **TargetYear**, **TargetValue**, **TargetType**, **TargetPercent**                           |
+--------------------+------------------------------------------------------------------------------------------------+
| `PSTAR`            | - **KPstar**                                                                                   |
|                    | - **PStar**                                                                                    |
|                    | - **PstarF**                                                                                   |
|                    | - **TargetYear**                                                                               |
+--------------------+------------------------------------------------------------------------------------------------+

: Table of AGEPRO input file keywords. {#tbl-2}

