
#' write AGEPRO json input file
#'
#' Write AGEPRO input file
#'
#' @param x x
#' @param file file
#'
#' @export
write_inpfile <- function(x, file) {

  #verify output
  if (!(is.list(x) && (length(x) == 16))) {
    stop("Invalid input object")
  }


}


#' AGEPRO version
#'
#' Sets/marks AGEPRO Calcuation Version
#'
#' @param legacy_version_string Version Character String generated by legacy
#' versions
#' @param version_number AGEPRO version
#'
set_version <- function(legacy_version_string = "AGEPRO VERSION 4.0",
                        version_number = "4.0.0.0") {
  return(list("legacyVer" = legacy_version_string,
              "ver" = version_number))
}

#' Case ID
#'
#' Set Case id
#'
#' @param id Case id
#'
set_case_id <- function(id = "REDFISH - RECRUITMENT MODEL 14") {
  return(id)
}

#' AGEPRO general options
#'
#' Sets general options for AGEPRO
#'
#' @param first_year First Year of prediction
#' @param last_year Last Year of prediction
#' @param first_age First Age Class
#' @param last_age Last Age Class
#' @param num_sims Number of Population Simulations
#' @param num_fleets Number of Fleets
#' @param num_models Number of Recruitment Models
#' @param seed Psuedo-random number seed
#' @param discard Are Discards Are Present
#'
set_general <- function(first_year,
                        last_year,
                        first_age,
                        last_age,
                        num_sims,
                        num_fleets,
                        num_models,
                        seed,
                        discard = FALSE) {

  if (seed == 0) {
    stop("Seed is 0")
  }

  return(list("nFYear": first_year,
              "nXYear": last_year,
              "nFAge": first_age,
              "nXAge": last_age,
              "nSims": num_sims,
              "nFleet": num_fleets,
              "nRecModel": num_models,
              "discFlag": if (TRUE) 1 else (0),
              "seed": seed))

}

#' Bootstrapping
#'
#' AGEPRO Bootstrapping options
#'
#' @param num_boot Number Of Bootstrap Operations
#' @param boot_factor Population scaling Factor
#' @param file Bootstrap File
#'
#' @importFrom here here
#'
set_bootstrap <- function(num_boot = 1000,
                          boot_factor = 1000,
                          file = here("inst", "Example1.BSN")) {

  return(list("nboot": num_boot,
              "bootFac": boot_factor,
              "bootFile":file))
}

#' Stochastic (Weight) Of Age
#'
#' Sets a Stochastic (Weight) of Age
#'
#' @param df data
#' @param sd error
#' @param flag flag
#' @param time_flag Time Varying
#'
#'
set_stochastic_weight_age <- function(df,
                                      sd,
                                      flag = 1,
                                      time_flag = TRUE) {


  if (flag == 1) {
    #From UI input
    if (time_flag) {
      #check nrows of df
      if (nrow(df) <= 1) {
        stop("Invalid Dataframe")
      }
      time_flag <- 1
    }else {
      if (nrow(df) > 1) {
        stop("Invalid Dataframe")
      }
      time_flag <- 0
    }

    return(list("flag":1,
                "timeFlag":time_flag,
                "value":df,
                "error":sd))

  } else if (flag == 2) {
    #From File: df is Filename
    return(list("flag":2,
                "timeFlag":time_flag,
                "value":df[1],
                "error":NULL))

  } else if (flag == 3) {
    #JAN-1 Stock Weights of AGE
    return(list("flag":3,
                "timeFlag":time_flag,
                "value":NULL,
                "error":NULL))

  } else if (flag == 4) {
    #SSB Weights Of Age
    return(list("flag":4,
                "timeFlag":time_flag,
                "value":NULL,
                "error":NULL))

  } else if (flag == 5) {
    #Mid-year/mean Weights
    return(list("flag":5,
                "timeFlag":time_flag,
                "value":NULL,
                "error":NULL))

  } else if (flag == 6) {
    #Use Catch Weights
    return(list("flag":6,
                "timeFlag":time_flag,
                "value":NULL,
                "error":NULL))
  }

}


#' Sets Stochastic age
#'
#' Sets a Stochastic parameter of Age
#'
#' @param valid_flag Valid flag
#'
set_stochastic_age <- function(valid_flag = c(1, 2)) {
  force(valid_flag)
  function(df, sd, flag, time_flag) {
    if (!flag %in% valid_flag) {
      stop("Invalid Stochastic Parameter of Age flag")
    }
    #Send to stochastic weight of age function
    return(set_stochastic_weight_age(df, sd, flag, time_flag))
  }

}
set_stock_weight <- set_stochastic_age(valid_flag = c(1, 2))
set_ssb_weight <- set_stochastic_age(valid_flag = c(1, 2, 3))
set_mean_weight <- set_stochastic_age(valid_flag = c(1, 2, 3, 4))
set_catch_weight <- set_stochastic_age(valid_flag = c(1, 2, 3, 4, 5))
set_discard_weight <- set_stochastic_age(valid_flag = c(1, 2, 3, 4, 5, 6))

set_maturity <- set_stochastic_age()
set_fishery <- set_stochastic_age()
set_natural_mortality <- set_stochastic_age()










new_inpfile <- function() {

  return(list())
}
