
#' write AGEPRO json input file
#'
#' Write AGEPRO input file
#'
#' @param x x
#' @param file file
#'
#' @export
write_inpfile <- function (x, file) {

  #verify output
  if(!(is.list(x) && (length(x) == 16)) ){
    stop("Invalid input object")
  }


}


#' AGEPRO version
#'
#' Sets/marks AGEPRO Calcuation Version
#'
#' @param legacyVersionString Version Character String generated by legacy versions
#' @param versionNumber AGEPRO version
#'
set_version <- function (legacyVersionString="AGEPRO VERSION 4.0",versionNumber="4.0.0.0") {
  return(list("legacyVersionString"=legacyVersionString,
              "versionNumber"=versionNumber))
}

#' Case ID
#'
#' Set Case id
#'
#' @param id Case id
#'
set_caseID <- function (id="REDFISH - RECRUITMENT MODEL 14"){
  return(id)
}

#' AGEPRO general options
#'
#' Sets general options for AGEPRO
#'
#' @param nFYear First Year of prediction
#' @param nXYear Last Year of prediction
#' @param nFAge First Age Class
#' @param nXAge Last Age Class
#' @param nSims Number of Population Simulations
#' @param nFleet Number of Fleets
#' @param nRecModel Number of Recruitment Models
#' @param seed Psuedo-random number seed
#' @param discard Are Discards Are Present
#'
set_general <- function (nFYear,nXYear,nFAge,nXAge,nSims,nFleet,nRecModel,seed,discard=FALSE)
{

  if(seed == 0){
    stop("Seed is 0")
  }

  return(list("nFYear": nFYear,
              "nXYear": nXYear,
              "nFAge": nFAge,
              "nXAge": nXAge,
              "nSims": nSims,
              "nFleet": nFleet,
              "nRecModel": nRecModel,
              "discFlag": if (TRUE) 1 else (0),
              "seed": seed))

}

#' Bootstrapping
#'
#' AGEPRO Bootstrapping options
#'
#' @param nboot Number Of Bootstrap Operations
#' @param bootFac Population scaling Factor
#' @param file Bootstrap File
#'
#' @importFrom here here
#'
set_bootstrap <- function (nboot=1000,
                           bootFac=1000,
                           file= here("inst","Example1.BSN")) {

  return(list("nboot": nboot,
              "bootFac": bootFac,
              "bootFile":file))
}

#' Stochastic (Weight) Of Age
#'
#' Sets a Stochastic (Weight) of Age
#'
#' @param df data
#' @param sd error
#' @param flag flag
#' @param timeFlag Time Varying
#'
#'
set_stochasticWeightAge <- function (df, sd, flag=1, timeFlag=TRUE) {


  if (flag == 1) {
    #From UI input
    if (timeFlag) {
      #check nrows of df
      if (nrow(df) <= 1) {
        stop("Invalid Dataframe")
      }
      timeFlag <- 1
    }
    else{
      if (nrow(df) > 1) {
        stop("Invalid Dataframe")
      }
      timeFlag <- 0
    }

    return(list("flag":1,
                "timeFlag":timeFlag,
                "value":df,
                "error":sd))

  } else if (flag == 2) {
    #From File: df is Filename
    return(list("flag":2,
                "timeFlag":timeFlag,
                "value":df[1],
                "error":NULL))

  } else if (flag == 3) {
    #JAN-1 Stock Weights of AGE
    return(list("flag":3,
                "timeFlag":timeFlag,
                "value":NULL,
                "error":NULL))

  } else if (flag == 4) {
    #SSB Weights Of Age
    return(list("flag":4,
                "timeFlag":timeFlag,
                "value":NULL,
                "error":NULL))

  } else if (flag == 5) {
    #Mid-year/mean Weights
    return(list("flag":5,
                "timeFlag":timeFlag,
                "value":NULL,
                "error":NULL))

  } else if (flag == 6) {
    #Use Catch Weights
    return(list("flag":6,
                "timeFlag":timeFlag,
                "value":NULL,
                "error":NULL))
  }

}

# set_stockWeight <- function (df, sd, flag=c(1,2), timeFlag=TRUE) {
#
#   #validate flag
#   flag <- match.arg(flag)
#   return(set_stochasticWeightAge(df, sd, flag,timeFlag))
# }
#
# set_ssbWeight <- function (df, sd, flag=c(1,2,3), timeFlag=TRUE) {
#   flag <- match.arg(flag)
#   return(set_stochasticWeightAge(df, sd, flag, timeFlag))
# }
#
# set_meanWeight <- function (df, sd, flag=c(1,2,3,4), timeFlag=TRUE) {
#   flag <- match.arg(flag)
#   return(set_stochasticWeightAge(df, sd, flag, timeFlag))
# }
#
# set_catchWeight <- function (df, sd, flag=c(1,2,3,4,5), timeFlag=TRUE) {
#   flag <- match.arg(flag)
#   return(set_stochasticWeightAge(df, sd, flag, timeFlag))
# }
#
# set_discardWeight <- function(df, sd, flag=c(1,2,3,4,5,6), timeFlag=TRUE) {
#   flag <- match.arg(flag)
#   return(set_stochasticWeightAge(df, sd, flag, timeFlag))
# }

# set_stochasticAge <- function(df, sd, flag=c(1,2), timeFlag=TRUE) {
#   if(!flag %in% c(1,2)){
#     stop("Invalid Stochastic Parameter of Age flag")
#   }
#   return(set_stochasticWeightAge(df, sd, flag, timeFlag))
# }

set_stochasticAge <- function(validFlag=c(1,2)) {
  force(validFlag)
  function(df, sd, flag, timeFlag) {
    if(!flag %in% validFlag){
      stop("Invalid Stochastic Parameter of Age flag")
    }
    return(set_stochasticWeightAge(df, sd, flag, timeFlag))
  }

}

set_stockWeight <- set_stochasticAge(validFlag = c(1,2))
set_ssbWeight <- set_stochasticAge(validFlag = c(1,2,3))
set_meanWeight <- set_stochasticAge(validFlag = c(1,2,3,4))
set_catchWeight <- set_stochasticAge(validFlag = c(1,2,3,4,5))
set_discardWeight <- set_stochasticAge(validFlag = c(1,2,3,4,5,6))

set_maturity <- set_stochasticAge()
set_fishery <- set_stochasticAge()



new_inpfile <- function () {

  version <- list("legacyVersionString"="AGEPRO VERSION 4.0",
                  "versionNumber"="4.0.0.0")

  caseID <- "REDFISH - RECRUITMENT MODEL 14"
  general <- list(
    "nFYear": 2004,
    "nXYear": 2009,
    "nFAge": 1,
    "nXAge": 26,
    "nSims": 100,
    "nFleet": 2,
    "nRecModel": 1,
    "discFlag": 0,
    "seed": 49667890
  )

  bootstrap <- list(
    "nboot" : 1000,
    "bootFac": 1000,
    "bootFile": ""
  )

  return(list())
}
